### ISSUE TITLE
Android NDK version build error

### ISSUE THREAD

**Issue by threearabawys** [feixuwu/UnrealEngine4-EZ-Mobile-Ads#7]
Hello, 

I implemented the plugin into my project, got my chartboost app ID and signature, plugged them into the editor, set the "Show Interstitial" node to chart boost and plugged it where I wanted... 

Now in the editor the ad never shows up and if i try a rewarded video ad It never fires success neither.
when I try to build it fails, unless I change the NDK API level option in the Android SDK section of my project settings to "latest" it builds the APK, but ofc it won't run on anything below marshmallow and my test devices is a kitkat phone so I can't confirm whether the ads are going to run or not.

Any help would be very much appreciated so thanks in advance :+1: 

BTW: I'm using UE 4.19, but I tried 4.18 and still got the same result.

**Comment by feixuwu** [comment]
Hi，all the mobile ads will never show on editor.
Please build my demo project and run it on the device, if it build success, you can click the button to see the ads on your phone.
if it can not build success, please check your build env, please read this document and install codeworks
https://docs.unrealengine.com/en-us/Platforms/Android/GettingStarted

if you have any problem, please feel free to email me. I’ll try my best to help, thanks very much!

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: threearabawys <notifications@github.com>
发送时间: Friday, May 11, 2018 11:48:05 PM
收件人: feixuwu/UnrealEngine4-EZ-Mobile-Ads
抄送: Subscribed
主题: [feixuwu/UnrealEngine4-EZ-Mobile-Ads] Android NDK version build error (#7)


Hello,

I implemented the plugin into my project, got my chartboost app ID and signature, plugged them into the editor, set the "Show Interstitial" node to chart boost and plugged it where I wanted...

Now in the editor the ad never shows up and if i try a rewarded video ad It never fires success neither.
when I try to build it fails, unless I change the NDK API level option in the Android SDK section of my project settings to "latest" it builds the APK, but ofc it won't run on anything below marshmallow and my test devices is a kitkat phone so I can't confirm whether the ads are going to run or not.

Any help would be very much appreciated so thanks in advance 👍

**Comment by feixuwu** [comment]
You can build your project success, so if you can install the apk on your device?
Why you have to set your ndk version higher then api-19?
Even though, you can still install the apk on your device, and do the test.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: threearabawys <notifications@github.com>
发送时间: Saturday, May 12, 2018 12:20:16 AM
收件人: feixuwu/UnrealEngine4-EZ-Mobile-Ads
抄送: xufeiwu; Comment
主题: Re: [feixuwu/UnrealEngine4-EZ-Mobile-Ads] Android NDK version build error (#7)


Thank you for the swift reply,
I can build my project successfully, only I have to set the NDK version to anything higher than API-19, but if I do I can't run it on my test device because it's API-19.

I tried an empty project but same result. I'll try the example project as well but I doubt it will build.

―

**Comment by feixuwu** [comment]
By the way, install codeworks to build unreal engine 4 project, unreal engine 4 official support the engine work with codeworks.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: threearabawys <notifications@github.com>
发送时间: Saturday, May 12, 2018 12:20:16 AM
收件人: feixuwu/UnrealEngine4-EZ-Mobile-Ads
抄送: xufeiwu; Comment
主题: Re: [feixuwu/UnrealEngine4-EZ-Mobile-Ads] Android NDK version build error (#7)


Thank you for the swift reply,
I can build my project successfully, only I have to set the NDK version to anything higher than API-19, but if I do I can't run it on my test device because it's API-19.

I tried an empty project but same result. I'll try the example project as well but I doubt it will build.

―

**Comment by threearabawys** [comment]
I can build it only if my ndk api is set to a value higher than 19 or set to "latest" , if its api 19 build fails and I get a console error.
I need to build with NDK 19 because I need the apk to run on kitkat ...

if I build on "latest" or 21 the apk just gives me a parsing error when I try to install it.

I'm sorry for the confusion.

**Comment by feixuwu** [comment]
Android ndk version should not affect the apk install on your device. Did you get any error message when you try to install apk on your device?

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: threearabawys <notifications@github.com>
发送时间: Saturday, May 12, 2018 12:50:50 AM
收件人: feixuwu/UnrealEngine4-EZ-Mobile-Ads
抄送: xufeiwu; Comment
主题: Re: [feixuwu/UnrealEngine4-EZ-Mobile-Ads] Android NDK version build error (#7)


I can build it only if my ndk api is set to a value higher than 19 or set to "latest" , if its api 19 build fails and I get a console error.
I need to build with NDK 19 because I need the apk to run on kitkat ...

if I build on "latest" or 21 the apk just gives me a parsing error when I try to install it.

I'm sorry for the confusion.

―

**Comment by threearabawys** [comment]
yes I get a "Parsing error" message when I try to install the apk.

If I set the NDK to "latest" I can't build the apk at all.

**Comment by threearabawys** [comment]
Ok, I just installed a marshmallow emulator, the ads work perfectly.

The only issue is that my app can only run on anroid 6 and higher :(

**Comment by threearabawys** [comment]
``<blockquote class="imgur-embed-pub" lang="en" data-id="a/XNhMntB" data-context="false"><a href="//imgur.com/XNhMntB"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>``

**Comment by threearabawys** [comment]
[https://i.imgur.com/ttxDE1P.png](url)

**Comment by feixuwu** [comment]
From the error message, you can see the error. So please change your android sdk min sdk to 15(android sdk version is not ndk version).

[cid:image001.png@01D3E9CB.59E09640]

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: threearabawys <notifications@github.com>
发送时间: Saturday, May 12, 2018 6:02:39 AM
收件人: feixuwu/UnrealEngine4-EZ-Mobile-Ads
抄送: xufeiwu; Comment
主题: Re: [feixuwu/UnrealEngine4-EZ-Mobile-Ads] Android NDK version build error (#7)


https://i.imgur.com/ttxDE1P.png<url>

―

**Comment by threearabawys** [comment]
That worked beautifully :)

I had "Minimum SDK Version" set to "9" ------ I set it to "15"
and "Target SDK Version" set to "14"     ------- I left it at "14"

and it worked, the game compiled and ran on my kitkat device.

Thank you so much for your assistance.
